
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.ParseException;
import java.time.LocalDate;
import java.time.temporal.ChronoUnit;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Work
 */
public class PlaceTimeDetails1 extends javax.swing.JFrame {

    public PlaceTimeDetails1() {
        initComponents();
        resIdDisplay.setText(uIDGenerator());
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        resIdDisplay = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Lucida Bright", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Travel Details");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(300, 30, 260, 50);

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Please fill the form below");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(370, 90, 180, 14);

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("ResID:");
        jPanel1.add(jLabel12);
        jLabel12.setBounds(220, 130, 100, 30);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Pick-Up Place:");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(220, 170, 100, 30);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Drop-Off Place:");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(220, 210, 100, 30);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Start Date:");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(220, 250, 100, 30);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("End Date:");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(220, 290, 100, 30);

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("License No:");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(220, 330, 100, 30);

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Car ID:");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(220, 370, 100, 30);

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("ViewCars");
        jLabel11.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel11MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel11);
        jLabel11.setBounds(380, 420, 70, 30);
        jPanel1.add(jTextField1);
        jTextField1.setBounds(350, 170, 240, 30);
        jPanel1.add(jTextField2);
        jTextField2.setBounds(350, 210, 240, 30);
        jPanel1.add(jTextField3);
        jTextField3.setBounds(350, 250, 240, 30);
        jPanel1.add(jTextField4);
        jTextField4.setBounds(350, 290, 240, 30);
        jPanel1.add(jTextField5);
        jTextField5.setBounds(350, 330, 240, 30);
        jPanel1.add(jTextField6);
        jTextField6.setBounds(350, 370, 240, 30);

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Eg:2017-03-21");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(630, 260, 90, 15);

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Eg:2017-03-21");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(630, 300, 90, 15);

        resIdDisplay.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(resIdDisplay);
        resIdDisplay.setBounds(350, 130, 110, 30);

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setText("Next>");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(360, 470, 110, 30);

        jLabel14.setIcon(new javax.swing.ImageIcon("C:\\Users\\Work\\Desktop\\Project\\wallpapers\\infiniti_g37s_car_3-wallpaper-960x540.jpg")); // NOI18N
        jPanel1.add(jLabel14);
        jLabel14.setBounds(0, 0, 900, 540);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 900, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 540, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        if((jTextField1.getText().length()==0)||(jTextField2.getText().length()==0)||(jTextField3.getText().length()==0)
                ||(jTextField4.getText().length()==0)||(jTextField5.getText().length()==0))
        {
            JOptionPane.showMessageDialog(null, "Please fill all fields");
        }
        else
        {
            String pickup      = jTextField1.getText();
            String dropoff     = jTextField2.getText();
            String startdate   = jTextField3.getText();
            String enddate     = jTextField4.getText();
            String licno       = jTextField5.getText();
            
          //  Date date = dateChooserCombo1.getDate();
            
            
            String cid = jTextField6.getText();
            
            /* if((CheckLicnoExists(licno))== false)
            {
            JOptionPane.showMessageDialog(null, "License Number is Wrong!");
            }
            else
            { */
            String resid = uIDGenerator();
            try {
                insertvalues(resid,pickup,dropoff,startdate,enddate,licno,cid);
            } catch (ClassNotFoundException | SQLException | ParseException ex) {
                Logger.getLogger(PlaceTimeDetails1.class.getName()).log(Level.SEVERE, null, ex);
            }
            Payment1 p = new Payment1();
            p.setVisible(true);
            p.pack();
            p.setLocationRelativeTo(null);
            p.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
            this.dispose();
            // }
            
        }// TODO add your handling code here:
    }//GEN-LAST:event_jButton1MouseClicked

    private void jLabel11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MouseClicked
        ViewCar1 vc = new ViewCar1();
        vc.setVisible(true);
        vc.pack();
        vc.setLocationRelativeTo(null);
        vc.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
    }//GEN-LAST:event_jLabel11MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PlaceTimeDetails1().setVisible(true);
            }
        });
    }
    private String uIDGenerator()
    {
        String uid="1";
        int id;
        try{
        Class.forName("oracle.jdbc.OracleDriver");
        Connection conn = DriverManager.getConnection("jdbc:oracle:thin:@activation.acronis.com:1521:orcl","scott","tiger");
        PreparedStatement st = conn.prepareStatement("select * from reservation order by resid");
        ResultSet rs = st.executeQuery();
        if(rs.next())
        {
            
            while(rs.next())
                uid=rs.getString(1);
            id=Integer.parseInt(uid);
            id++;
            uid=String.valueOf(id);
        }
        
        }
        catch(ClassNotFoundException | SQLException e)
        {
            
        }
        return uid;
    }
    public void insertvalues(String resid,String pickup,String dropoff,String startdate,String enddate,String licno,String cid) throws ClassNotFoundException, SQLException, ParseException
    {
        Class.forName("oracle.jdbc.OracleDriver");
        Connection conn = DriverManager.getConnection("jdbc:oracle:thin:@activation.acronis.com:1521:orcl","scott","tiger");
        PreparedStatement st;
        
        //Custom date format
     //   Date date1=(Date) new SimpleDateFormat("dd/MM/yyyy").parse(startdate);
      //  Date date2=(Date) new SimpleDateFormat("dd/MM/yyyy").parse(enddate);
        LocalDate date1 = LocalDate.parse(startdate);
        LocalDate date2 = LocalDate.parse(enddate);
        long range;
        range = ChronoUnit.DAYS.between(date1,date2);
        System.out.println(range);
        st = conn.prepareStatement("insert into reservation(RESID,PICKUP,DROPOFF,STARTDATE,ENDDATE,LICNO,CID,NOOFDAYS)values(?,?,?,?,?,?,?,?)");
        st.setString(1,resid);
        st.setString(2,pickup);
        st.setString(3,dropoff);
        st.setString(4,startdate);
        st.setString(5,enddate);
        st.setString(6,licno);
        st.setString(7,cid);
        st.setLong(8,range);
        int a = st.executeUpdate();
        if(a>0)
        {
            System.out.println("Row Updated Successfully");
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JLabel resIdDisplay;
    // End of variables declaration//GEN-END:variables
}
