
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Work
 */
public class RegisterForm1 extends javax.swing.JFrame {

    /**
     * Creates new form RegisterForm1
     */
    public RegisterForm1() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jmobile = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jfirstname = new javax.swing.JLabel();
        jlastname = new javax.swing.JLabel();
        jemail = new javax.swing.JLabel();
        jpassword = new javax.swing.JLabel();
        jusername = new javax.swing.JLabel();
        jretypepassword = new javax.swing.JLabel();
        jmobiletext = new javax.swing.JTextField();
        jfirstnametext = new javax.swing.JTextField();
        jlastnametext = new javax.swing.JTextField();
        jemailtext = new javax.swing.JTextField();
        jusernametext = new javax.swing.JTextField();
        jretypepasswordtext = new javax.swing.JPasswordField();
        jpasswordtext = new javax.swing.JPasswordField();
        jregister = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        jmobile.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jmobile.setForeground(new java.awt.Color(255, 255, 255));
        jmobile.setText("Mobile:");
        jPanel1.add(jmobile);
        jmobile.setBounds(270, 370, 60, 30);

        jLabel2.setFont(new java.awt.Font("Lucida Bright", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Register Form");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(330, 30, 270, 60);

        jfirstname.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jfirstname.setForeground(new java.awt.Color(255, 255, 255));
        jfirstname.setText("First Name:");
        jPanel1.add(jfirstname);
        jfirstname.setBounds(270, 130, 80, 20);

        jlastname.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jlastname.setForeground(new java.awt.Color(255, 255, 255));
        jlastname.setText("Last Name:");
        jPanel1.add(jlastname);
        jlastname.setBounds(270, 170, 70, 30);

        jemail.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jemail.setForeground(new java.awt.Color(255, 255, 255));
        jemail.setText("Email-ID:");
        jPanel1.add(jemail);
        jemail.setBounds(270, 210, 70, 30);

        jpassword.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jpassword.setForeground(new java.awt.Color(255, 255, 255));
        jpassword.setText("Password:");
        jPanel1.add(jpassword);
        jpassword.setBounds(270, 300, 70, 17);

        jusername.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jusername.setForeground(new java.awt.Color(255, 255, 255));
        jusername.setText("Username:");
        jPanel1.add(jusername);
        jusername.setBounds(270, 250, 70, 30);

        jretypepassword.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jretypepassword.setForeground(new java.awt.Color(255, 255, 255));
        jretypepassword.setText("Re-Type Password:");
        jPanel1.add(jretypepassword);
        jretypepassword.setBounds(270, 330, 130, 30);

        jmobiletext.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jmobiletextKeyTyped(evt);
            }
        });
        jPanel1.add(jmobiletext);
        jmobiletext.setBounds(410, 370, 210, 30);

        jfirstnametext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jfirstnametextActionPerformed(evt);
            }
        });
        jPanel1.add(jfirstnametext);
        jfirstnametext.setBounds(410, 130, 210, 30);
        jPanel1.add(jlastnametext);
        jlastnametext.setBounds(410, 170, 210, 30);
        jPanel1.add(jemailtext);
        jemailtext.setBounds(410, 210, 210, 30);
        jPanel1.add(jusernametext);
        jusernametext.setBounds(410, 250, 210, 30);
        jPanel1.add(jretypepasswordtext);
        jretypepasswordtext.setBounds(410, 330, 210, 30);
        jPanel1.add(jpasswordtext);
        jpasswordtext.setBounds(410, 290, 210, 30);

        jregister.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jregister.setForeground(new java.awt.Color(255, 255, 255));
        jregister.setText("Register");
        jregister.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jregister.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jregisterMouseClicked(evt);
            }
        });
        jPanel1.add(jregister);
        jregister.setBounds(410, 440, 60, 20);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Back");
        jLabel3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel3);
        jLabel3.setBounds(420, 480, 27, 14);

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Work\\Desktop\\Project\\wallpapers\\c63_amg-wallpaper-960x540.jpg")); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 900, 540);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 900, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 539, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jfirstnametextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jfirstnametextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jfirstnametextActionPerformed

    private void jregisterMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jregisterMouseClicked
        char[] pas1 = jpasswordtext.getPassword();
        String pas = String.copyValueOf(pas1);
        
        
        char[] rpas1 = jretypepasswordtext.getPassword();
        String rpas = String.copyValueOf(rpas1);
        
        
        if((jfirstnametext.getText().length()==0)||(jlastnametext.getText().length()==0)||(jemailtext.getText().length()==0)
                ||(jusernametext.getText().length()==0)||
                (jmobiletext.getText().length()==0))
        {
            JOptionPane.showMessageDialog(null, "Please fill all fields");
        }
        else if((jpasswordtext.getPassword().length==0) || (jretypepasswordtext.getPassword().length==0))  // Checking for empty field
        {
            JOptionPane.showMessageDialog(null, "Please fill up all fields");
        }
        
        if(pas.equals(rpas))
        {
            String firstname      = jfirstnametext.getText();
            String lastname       = jlastnametext.getText();
            String emailid        = jemailtext.getText();
            String username       = jusernametext.getText();
            String mobile         = jmobiletext.getText();
            char[] password       = jpasswordtext.getPassword();
            char[] retypepassword = jretypepasswordtext.getPassword();
        
        
            try 
            {
                if((CheckUsernameExists(username))== true)
                {
                    JOptionPane.showMessageDialog(null, "Username exists!");
                }
                else
                {   
                    String pass = String.copyValueOf(password);
               
                    insertvalues(firstname,lastname,emailid,username,mobile,pass);
                
                    LoginForm1 rgf = new LoginForm1();
                    rgf.setVisible(true);
                    rgf.pack();
                    rgf.setLocationRelativeTo(null);
                    rgf.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
                    this.dispose();
                }
            } 
            catch (ClassNotFoundException | SQLException ex) 
            {
                Logger.getLogger(RegisterForm.class.getName()).log(Level.SEVERE, null, ex);
            }
        
        }
        else if(pas!=rpas)
        {
            JOptionPane.showMessageDialog(null, "Passwords do not match!");
            
        }// TODO add your handling code here:
    }//GEN-LAST:event_jregisterMouseClicked

    private void jmobiletextKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jmobiletextKeyTyped
        char enter = evt.getKeyChar();
        if(!(Character.isDigit(enter))){
            evt.consume();
        }// TODO add your handling code here:
    }//GEN-LAST:event_jmobiletextKeyTyped

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
                    LoginForm1 rgf = new LoginForm1();
                    rgf.setVisible(true);
                    rgf.pack();
                    rgf.setLocationRelativeTo(null);
                    rgf.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
                    this.dispose();// TODO add your handling code here:
    }//GEN-LAST:event_jLabel3MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegisterForm1().setVisible(true);
            }
        });
    }
    /**
     *
     * @param firstname
     * @param lastname
     * @param emailid
     * @param username
     * @param mobile
     * @param password
     * @throws java.lang.ClassNotFoundException
     * @throws java.sql.SQLException
     */
    public void insertvalues(String firstname,String lastname,String emailid,String username,String mobile,String password) throws ClassNotFoundException, SQLException
    {
        Class.forName("oracle.jdbc.OracleDriver");
        Connection conn = DriverManager.getConnection("jdbc:oracle:thin:@activation.acronis.com:1521:orcl","scott","tiger");
        PreparedStatement st = conn.prepareStatement("insert into login1(USERNAME,FIRSTNAME,PASSWORD,EMAILID,LASTNAME,MOBILE)values(?,?,?,?,?,?)");
        st.setString(1,username);
        st.setString(2,firstname);
        st.setString(3,password);
        st.setString(4,emailid);
        st.setString(5,lastname);
        st.setString(6,mobile);
        int a = st.executeUpdate();
        if(a>0)
        {
            System.out.println("Row Updated Successfully");
        }
    }
    public static boolean CheckUsernameExists(String username) throws ClassNotFoundException, SQLException
    {
        boolean usernameExists = false;

        Class.forName("oracle.jdbc.OracleDriver");
        Connection conn = DriverManager.getConnection("jdbc:oracle:thin:@activation.acronis.com:1521:orcl","scott","tiger");
        PreparedStatement st = conn.prepareStatement("select * from login1 order by username desc");
        ResultSet r1=st.executeQuery();
        
        String usernameCounter;
        if(r1.next())
        {
            usernameCounter =  r1.getString("username");
            if(usernameCounter.equals(username)) //this part does not happen even if it should
            {
                System.out.println("It already exists");
                usernameExists = true;
            }
        }

        return usernameExists;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel jemail;
    private javax.swing.JTextField jemailtext;
    private javax.swing.JLabel jfirstname;
    private javax.swing.JTextField jfirstnametext;
    private javax.swing.JLabel jlastname;
    private javax.swing.JTextField jlastnametext;
    private javax.swing.JLabel jmobile;
    private javax.swing.JTextField jmobiletext;
    private javax.swing.JLabel jpassword;
    private javax.swing.JPasswordField jpasswordtext;
    private javax.swing.JLabel jregister;
    private javax.swing.JLabel jretypepassword;
    private javax.swing.JPasswordField jretypepasswordtext;
    private javax.swing.JLabel jusername;
    private javax.swing.JTextField jusernametext;
    // End of variables declaration//GEN-END:variables
}
