
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Work
 */
public class RegisterForm extends javax.swing.JFrame {

    /**
     * Creates new form RegisterForm
     */
    public RegisterForm() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jfirstname = new javax.swing.JLabel();
        jlastname = new javax.swing.JLabel();
        jemail = new javax.swing.JLabel();
        jusername = new javax.swing.JLabel();
        jpassword = new javax.swing.JLabel();
        jretypepassword = new javax.swing.JLabel();
        jmobile = new javax.swing.JLabel();
        jregister = new javax.swing.JLabel();
        jfirstnametext = new javax.swing.JTextField();
        jlastnametext = new javax.swing.JTextField();
        jemailtext = new javax.swing.JTextField();
        jusernametext = new javax.swing.JTextField();
        jpasswordtext = new javax.swing.JPasswordField();
        jretypepasswordtext = new javax.swing.JPasswordField();
        jmobiletext = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(34, 49, 63));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(240, 240, 240));
        jLabel1.setText("Registration Form");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(136, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(149, 149, 149))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                .addContainerGap())
        );

        jfirstname.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jfirstname.setText("First Name");

        jlastname.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jlastname.setText("Last Name");

        jemail.setText("Email-Id");

        jusername.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jusername.setText("Username");

        jpassword.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jpassword.setText("Password");

        jretypepassword.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jretypepassword.setText("Re-Type Password");

        jmobile.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jmobile.setText("Mobile");

        jregister.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jregister.setText("Register");
        jregister.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jregister.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jregisterMouseClicked(evt);
            }
        });

        jfirstnametext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jfirstnametextActionPerformed(evt);
            }
        });

        jemailtext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jemailtextActionPerformed(evt);
            }
        });

        jmobiletext.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jmobiletextKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jlastname, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jfirstname, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jemail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jpassword)
                                .addComponent(jusername)))
                        .addGap(70, 70, 70)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jemailtext, javax.swing.GroupLayout.DEFAULT_SIZE, 199, Short.MAX_VALUE)
                            .addComponent(jpasswordtext)
                            .addComponent(jusernametext)
                            .addComponent(jlastnametext)
                            .addComponent(jfirstnametext)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jretypepassword)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                                .addComponent(jretypepasswordtext, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jmobile)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jregister)
                                    .addComponent(jmobiletext, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(82, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jfirstname)
                    .addComponent(jfirstnametext, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlastname)
                    .addComponent(jlastnametext, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jemailtext, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jemail))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jusername)
                    .addComponent(jusernametext, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jpassword)
                    .addComponent(jpasswordtext, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jretypepassword)
                    .addComponent(jretypepasswordtext, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jmobile)
                    .addComponent(jmobiletext, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(54, 54, 54)
                .addComponent(jregister)
                .addContainerGap(124, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jfirstnametextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jfirstnametextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jfirstnametextActionPerformed

    private void jregisterMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jregisterMouseClicked
        char[] pas1 = jpasswordtext.getPassword();
        String pas = String.copyValueOf(pas1);
        
        
        char[] rpas1 = jretypepasswordtext.getPassword();
        String rpas = String.copyValueOf(rpas1);
        
        
        if((jfirstnametext.getText().length()==0)||(jlastnametext.getText().length()==0)||(jemailtext.getText().length()==0)
                ||(jusernametext.getText().length()==0)||
                (jmobiletext.getText().length()==0))
        {
            JOptionPane.showMessageDialog(null, "Please fill all fields");
        }
        else if((jpasswordtext.getPassword().length==0) || (jretypepasswordtext.getPassword().length==0))  // Checking for empty field
        {
            JOptionPane.showMessageDialog(null, "Please fill up all fields");
        }
        
        if(pas.equals(rpas))
        {
            String firstname      = jfirstnametext.getText();
            String lastname       = jlastnametext.getText();
            String emailid        = jemailtext.getText();
            String username       = jusernametext.getText();
            String mobile         = jmobiletext.getText();
            char[] password       = jpasswordtext.getPassword();
            char[] retypepassword = jretypepasswordtext.getPassword();
        
        
            try 
            {
                if((CheckUsernameExists(username))== true)
                {
                    JOptionPane.showMessageDialog(null, "Username exists!");
                }
                else
                {   
                    String pass = String.copyValueOf(password);
               
                    insertvalues(firstname,lastname,emailid,username,mobile,pass);
                
                    LoginForm rgf = new LoginForm();
                    rgf.setVisible(true);
                    rgf.pack();
                    rgf.setLocationRelativeTo(null);
                    rgf.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
                    this.dispose();
                }
            } 
            catch (ClassNotFoundException | SQLException ex) 
            {
                Logger.getLogger(RegisterForm.class.getName()).log(Level.SEVERE, null, ex);
            }
        
        }
        else if(pas!=rpas)
        {
            JOptionPane.showMessageDialog(null, "Passwords do not match!");
            
        }
    }//GEN-LAST:event_jregisterMouseClicked

    /**
     *
     * @param firstname
     * @param lastname
     * @param emailid
     * @param username
     * @param mobile
     * @param password
     * @throws java.lang.ClassNotFoundException
     * @throws java.sql.SQLException
     */
    public void insertvalues(String firstname,String lastname,String emailid,String username,String mobile,String password) throws ClassNotFoundException, SQLException
    {
        Class.forName("oracle.jdbc.OracleDriver");
        Connection conn = DriverManager.getConnection("jdbc:oracle:thin:@activation.acronis.com:1521:orcl","scott","tiger");
        PreparedStatement st = conn.prepareStatement("insert into login1(USERNAME,FIRSTNAME,PASSWORD,EMAILID,LASTNAME,MOBILE)values(?,?,?,?,?,?)");
        st.setString(1,username);
        st.setString(2,firstname);
        st.setString(3,password);
        st.setString(4,emailid);
        st.setString(5,lastname);
        st.setString(6,mobile);
        int a = st.executeUpdate();
        if(a>0)
        {
            System.out.println("Row Updated Successfully");
        }
    }
    public static boolean CheckUsernameExists(String username) throws ClassNotFoundException, SQLException
    {
        boolean usernameExists = false;

        Class.forName("oracle.jdbc.OracleDriver");
        Connection conn = DriverManager.getConnection("jdbc:oracle:thin:@activation.acronis.com:1521:orcl","scott","tiger");
        PreparedStatement st = conn.prepareStatement("select * from login1 order by username desc");
        ResultSet r1=st.executeQuery();
        
        String usernameCounter;
        if(r1.next())
        {
            usernameCounter =  r1.getString("username");
            if(usernameCounter.equals(username)) //this part does not happen even if it should
            {
                System.out.println("It already exists");
                usernameExists = true;
            }
        }

        return usernameExists;
    }
    private void jemailtextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jemailtextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jemailtextActionPerformed

    private void jmobiletextKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jmobiletextKeyTyped
        char enter = evt.getKeyChar();
        if(!(Character.isDigit(enter))){
            evt.consume();
        }
        
    }//GEN-LAST:event_jmobiletextKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegisterForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegisterForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegisterForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegisterForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new RegisterForm().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel jemail;
    private javax.swing.JTextField jemailtext;
    private javax.swing.JLabel jfirstname;
    private javax.swing.JTextField jfirstnametext;
    private javax.swing.JLabel jlastname;
    private javax.swing.JTextField jlastnametext;
    private javax.swing.JLabel jmobile;
    private javax.swing.JTextField jmobiletext;
    private javax.swing.JLabel jpassword;
    private javax.swing.JPasswordField jpasswordtext;
    private javax.swing.JLabel jregister;
    private javax.swing.JLabel jretypepassword;
    private javax.swing.JPasswordField jretypepasswordtext;
    private javax.swing.JLabel jusername;
    private javax.swing.JTextField jusernametext;
    // End of variables declaration//GEN-END:variables
}
