
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Work
 */
public class ViewCarAdmin1 extends javax.swing.JFrame {

    /**
     * Creates new form ViewCarAdmin1
     */
    public ViewCarAdmin1() {
        initComponents();
        this.setLocationRelativeTo(null);
        show_car();
    }
    public ArrayList<car> userList(){
        ArrayList<car> usersList =  new  ArrayList<>();
        
        try{
            
            Connection conn=DriverManager.getConnection("jdbc:oracle:thin:@activation.acronis.com:1521:orcl","scott","tiger");
            String query1="SELECT * FROM car ORDER BY CID";
            Statement st=conn.createStatement();
            ResultSet rs=st.executeQuery(query1);
            car car1;
            while(rs.next())
            {
                car1 = new car(rs.getString("CID"),rs.getString("BRAND"),rs.getInt("SEATINGCAPACITY"),rs.getInt("PRICEPERDAY"),rs.getString("MODELNAME"),rs.getString("FUEL"));
               usersList.add(car1);
            }
            
        }
        catch(SQLException e)
        {
            
            JOptionPane.showMessageDialog(null,e); 
        }
        return usersList;
    }
    public void show_car(){
        ArrayList<car> list=userList();
        DefaultTableModel model;
        model = (DefaultTableModel)jTable1.getModel();
       Object[] row=new Object[6];
       for(int i=0;i<list.size();i++)
       {
           row[0]=list.get(i).getCID();
           row[1]=list.get(i).getBRAND();
           row[2]=list.get(i).getSEATINGCAPACITY();
           row[3]=list.get(i).getPRICEPERDAY();
           row[4]=list.get(i).getMODELNAME();
           row[5]=list.get(i).getFUEL();
           
           model.addRow(row);
           
           
                   
                   
                   
       }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "CID", "BRAND", "SEATINGCAPACITY", "PRICEPERDAY", "MODELNAME", "FUEL"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(170, 100, 570, 330);

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setText("<Back to Admin Panel");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(350, 460, 210, 25);

        jLabel1.setFont(new java.awt.Font("Lucida Bright", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Cars");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(420, 30, 100, 50);

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\Work\\Desktop\\Project\\wallpapers\\black_background_leather-wallpaper-960x540.jpg")); // NOI18N
        jPanel1.add(jLabel2);
        jLabel2.setBounds(0, 0, 900, 540);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 900, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 540, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
            AdminPanel1 ap = new AdminPanel1();
           ap.setVisible(true);
           ap.pack();
           ap.setLocationRelativeTo(null);
           ap.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
           this.dispose();// TODO add your handling code here:
    }//GEN-LAST:event_jButton1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewCarAdmin1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
